### ISSUE TITLE
Bugs, fixes and updates - 28/5

### ISSUE THREAD

**Issue by notshi** [devinit/D-Portal#106]
- [x] Show workings out / Methodology for each page (https://github.com/devinit/D-Portal/issues/99)
- [x] Automated d-portal updating (https://github.com/IATI/D-Portal/issues/97)
- [x] State when d-portal has updated (https://github.com/devinit/D-Portal/issues/94)
- [x] List of Ignored budgets (https://github.com/IATI/D-Portal/issues/98)
- [x] Confusing read more link (https://github.com/IATI/D-Portal/issues/95)
- [x] News page (https://github.com/IATI/D-Portal/issues/100)
- [x] Fix link in about page to old site (https://github.com/IATI/D-Portal/issues/105)
- [x] About page has been updated with new text provided
- [x] BUG - Example queries return no data (https://github.com/IATI/D-Portal/issues/90)
- [x] BUG - {total_projects} 
- [x] BUG - adjust the way valid budgets are selected
- [x] ~~CRS / IATI Spend / Budget table headers to link to popup for explanation (need text from Bill)~~
- [x] ~~Turn hover states into pop-ups where we can (for tablets)~~

Update 5/6
- [x] Add "coming soon" to install section until populated
- [x] CRS table to include dashes where appropriate just like d-portal
- [x] d-portal site: Click-through on "0" should display explanation
- [x] Add milestones (Matt)
- [x] Add Google Group (Matt)
- [x] FEATURE - Publisher Stats (possible solution for https://github.com/devinit/D-Portal/issues/103 & https://github.com/devinit/D-Portal/issues/99)
